[opener]
emacs = [
  { run = 'emacsclient -c -a "emacs-pgtk --init-directory ~/.config/emacs" "$@"', desc = "Emacs", orphan = true },
]
system = [
  { run = 'for path in "$@"; do xdg-open "$path"; done', desc = "Open with default app", orphan = true },
]

[open]
rules = [
  { mime = "text/*", use = "emacs" },
  { mime = "application/json", use = "emacs" },
  { mime = "application/toml", use = "emacs" },
  { mime = "application/xml", use = "emacs" },
  { mime = "application/pdf", use = "system" },
]
